import { Activity, BedDouble, CalendarDays, ChevronRight, Dumbbell, HeartPulse, Timer, Utensils, Waves } from "lucide-react";
import { useLocation } from "wouter";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader, Section, Metric, Panel, ProgressBar, Empty } from "@/components/os-ui";
import { PHASES, baselineDeviation, daysBetween, formatDate, movingAverage, rollingAverage, startOfWeek, trainingLoad, trendChange, useFitnessStore, type ActivityEntry } from "@/lib/localStore";
import { DEFAULT_WEEKLY_SCHEDULE } from "@shared/trainingPlan";

const chartValue = (value: number | undefined) => typeof value === "number" ? Math.round(value * 10) / 10 : null;

function TrendChart({ data, lines, emptyLabel = "记录至少两次后显示趋势" }: { data: Array<Record<string, string | number | null>>; lines: Array<{ dataKey: string; color: string; name: string }>; emptyLabel?: string }) {
  if (data.length < 2) return <Empty><p className="text-sm">{emptyLabel}</p></Empty>;
  return <div className="h-56 w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: -18 }}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)" /><XAxis dataKey="date" tick={{ fontSize: 10 }} tickLine={false} axisLine={false} /><YAxis tick={{ fontSize: 10 }} tickLine={false} axisLine={false} width={42} /><Tooltip contentStyle={{ borderRadius: 8, border: "1px solid var(--border)", background: "var(--card)" }} /><Line type="monotone" dataKey={lines[0].dataKey} name={lines[0].name} stroke={lines[0].color} strokeWidth={2} dot={{ r: 2 }} connectNulls />{lines.slice(1).map(line => <Line key={line.dataKey} type="monotone" dataKey={line.dataKey} name={line.name} stroke={line.color} strokeWidth={2} dot={{ r: 2 }} connectNulls />)}</LineChart></ResponsiveContainer></div>;
}

const bestObserved = (activities: ActivityEntry[], matcher: (exercise: string) => boolean) => {
  const values = activities.filter(activity => activity.completed).flatMap(activity => (activity.sets ?? []).filter(set => matcher(set.exercise) && typeof set.weight === "number").map(set => set.weight!));
  return values.length ? Math.max(...values) : undefined;
};

export default function Dashboard() {
  const { state } = useFitnessStore(); const [, go] = useLocation();
  const today = formatDate(); const week = startOfWeek();
  const phase = PHASES[state.settings.phase]; const phaseWeeks = state.settings.phaseDurationWeeks || phase.weeks; const weekNumber = Math.min(phaseWeeks, Math.floor(daysBetween(state.settings.phaseStarted) / 7) + 1);
  const weekActivities = state.activities.filter(a => a.date >= week && a.date <= today && a.completed); const weeklyTrainingLoad = Math.round(weekActivities.reduce((sum, activity) => sum + trainingLoad(activity), 0));
  const strength = weekActivities.filter(a => a.type === "strength").length; const swimming = weekActivities.filter(a => a.type === "swimming"); const tennis = weekActivities.filter(a => a.type === "tennis"); const boxing = weekActivities.filter(a => a.type === "boxing");
  const weeklySchedule = state.weeklySchedule?.length ? state.weeklySchedule : DEFAULT_WEEKLY_SCHEDULE;
  const strengthTarget = weeklySchedule.filter(item => item.type === "strength").length;
  const strengthRate = strengthTarget ? Math.min(100, Math.round(strength / strengthTarget * 100)) : 0;
  const bodyAvg = movingAverage(state.body, 7); const latest = [...state.body].sort((a, b) => b.date.localeCompare(a.date))[0];
  const nutritionWeek = state.nutrition.filter(n => n.date >= week && n.date <= today); const targets = state.settings.nutritionTargets;
  const proteinRate = nutritionWeek.length ? Math.round(nutritionWeek.filter(n => (n.protein ?? 0) >= targets.protein).length / nutritionWeek.length * 100) : 0;
  const calorieAverage = rollingAverage(state.nutrition, 7, entry => entry.calories); const fruitRate = nutritionWeek.length ? Math.round(nutritionWeek.filter(n => (n.fruitServings ?? 0) >= targets.fruit).length / nutritionWeek.length * 100) : 0; const vegetableRate = nutritionWeek.length ? Math.round(nutritionWeek.filter(n => (n.vegetableServings ?? 0) >= targets.vegetables).length / nutritionWeek.length * 100) : 0;
  const currentCarbDay = state.nutrition.find(n => n.date === today)?.carbDay ?? state.carbDayOverrides?.[today] ?? state.weeklyMealPlan?.dayPlans.find(day => day.date === today)?.carbDay ?? "medium";
  const sleep = rollingAverage(state.recovery, 7, entry => entry.sleepHours); const hrv = rollingAverage(state.recovery, 7, entry => entry.hrv); const restingHr = rollingAverage(state.recovery, 7, entry => entry.restingHr); const whoopRecovery = rollingAverage(state.recovery, 7, entry => entry.whoopRecovery);
  const sleepBaseline = baselineDeviation(state.recovery, entry => entry.sleepHours); const hrvBaseline = baselineDeviation(state.recovery, entry => entry.hrv); const restingHrBaseline = baselineDeviation(state.recovery, entry => entry.restingHr); const whoopBaseline = baselineDeviation(state.recovery, entry => entry.whoopRecovery);
  const signed = (value: number | undefined) => value === undefined ? "—" : `${value > 0 ? "+" : ""}${value.toFixed(1)}`;
  const bodyChart = [...state.body].sort((a, b) => a.date.localeCompare(b.date)).slice(-14).map(entry => ({ date: entry.date.slice(5), weight: chartValue(entry.weight), waist: chartValue(entry.waist), bodyFat: chartValue(entry.bodyFat) }));
  const recoveryChart = [...state.recovery].sort((a, b) => a.date.localeCompare(b.date)).slice(-14).map(entry => ({ date: entry.date.slice(5), sleep: chartValue(entry.sleepHours), hrv: chartValue(entry.hrv), restingHr: chartValue(entry.restingHr), whoop: chartValue(entry.whoopRecovery) }));
  const benchmarkRows = [
    { key: "squat" as const, label: "深蹲", target: state.settings.performanceBenchmarks.squat, observed: bestObserved(state.activities, exercise => /深蹲|squat/i.test(exercise)) },
    { key: "bench" as const, label: "卧推", target: state.settings.performanceBenchmarks.bench, observed: bestObserved(state.activities, exercise => /卧推|bench/i.test(exercise)) },
    { key: "pulling" as const, label: "拉类动作", target: state.settings.performanceBenchmarks.pulling, observed: bestObserved(state.activities, exercise => /引体|下拉|划船|pull|row/i.test(exercise)) },
    { key: "longestFreestyleM" as const, label: "最长连续自由泳", target: state.settings.performanceBenchmarks.longestFreestyleM, observed: Math.max(0, ...state.activities.filter(activity => activity.completed).map(activity => activity.longestFreestyleM ?? 0)) || undefined },
  ];
  return <div className="pb-10">
    <PageHeader eyebrow="Personal Fitness OS" title="Dashboard" description={`${today} · ${phase.label} · 第 ${weekNumber} / ${phaseWeeks} 周`} action={<button onClick={() => go("/log")} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">+ 快速记录</button>} />
    <Panel className="mb-6 flex items-center justify-between gap-4 border-primary/30 bg-primary/5"><div><p className="text-xs font-medium text-primary">CURRENT PHASE</p><p className="mt-1 text-lg font-semibold">{phase.label}</p><p className="text-sm text-muted-foreground">{phase.subtitle}</p></div><div className="text-right"><p className="text-3xl font-semibold">{weekNumber}<span className="text-base text-muted-foreground">/{phaseWeeks}</span></p><p className="text-xs text-muted-foreground">周进度</p></div></Panel>
    <Section title="Body" meta="趋势优先，不对单日数据过度反应"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="当前体重" value={latest?.weight !== undefined ? `${latest.weight.toFixed(1)} kg` : "—"} detail={latest?.date ?? "尚未记录"} /><Metric label="7 日平均" value={bodyAvg !== undefined ? `${bodyAvg.toFixed(1)} kg` : "—"} detail="移动平均" /><Metric label="腰围" value={latest?.waist !== undefined ? `${latest.waist.toFixed(1)} cm` : "—"} detail={signed(trendChange(state.body, 7, entry => entry.waist)) + " / 7 日"} /><Metric label="体脂估计" value={latest?.bodyFat !== undefined ? `${latest.bodyFat.toFixed(1)}%` : "—"} detail={signed(trendChange(state.body, 7, entry => entry.bodyFat)) + " / 7 日"} /></div><Panel className="mt-3"><p className="mb-2 text-sm font-medium">体成分趋势</p><TrendChart data={bodyChart} lines={[{ dataKey: "weight", color: "var(--chart-1)", name: "体重 kg" }, { dataKey: "waist", color: "var(--chart-2)", name: "腰围 cm" }, { dataKey: "bodyFat", color: "var(--chart-3)", name: "体脂 %" }]} /></Panel></Section>
    <div className="mt-6 grid gap-6 md:grid-cols-2"><Section title="Training" meta={strengthTarget ? `${strength} / ${strengthTarget} 次力量` : "未安排力量训练"}><Panel><div className="grid grid-cols-2 gap-4 md:grid-cols-3"><div><p className="text-xs text-muted-foreground">游泳</p><p className="mt-1 text-xl font-semibold">{swimming.length} <span className="text-sm font-normal text-muted-foreground">次</span></p><p className="text-xs text-muted-foreground">{(swimming.reduce((s, a) => s + (a.distanceM ?? 0), 0) / 1000).toFixed(1)} km</p></div><div><p className="text-xs text-muted-foreground">网球</p><p className="mt-1 text-xl font-semibold">{tennis.length} <span className="text-sm font-normal text-muted-foreground">次</span></p><p className="text-xs text-muted-foreground">{Math.round(tennis.reduce((s, a) => s + a.durationMin, 0) / 60 * 10) / 10} 小时</p></div><div><p className="text-xs text-muted-foreground">拳击</p><p className="mt-1 text-xl font-semibold">{boxing.length} <span className="text-sm font-normal text-muted-foreground">次</span></p><p className="text-xs text-muted-foreground">{boxing.reduce((s, a) => s + a.durationMin, 0)} min</p></div></div><div className="mt-4"><div className="mb-2 flex justify-between text-xs"><span>本周力量完成度</span><span>{strengthRate}%</span></div><ProgressBar value={strength} max={Math.max(strengthTarget, 1)} /></div><p className="mt-3 text-xs text-muted-foreground">本周总训练时长 {weekActivities.reduce((s, a) => s + a.durationMin, 0)} min</p><p className="mt-1 text-xs text-muted-foreground">本周训练负荷 {weeklyTrainingLoad} AU</p><button onClick={() => go("/plan")} className="mt-4 flex items-center text-sm text-primary">查看本周计划 <ChevronRight className="ml-1 h-4 w-4" /></button></Panel></Section>
      <Section title="Nutrition" meta="只显示高价值指标"><Panel className="space-y-4"><div><div className="flex justify-between text-sm"><span>蛋白质达标</span><strong>{proteinRate}%</strong></div><ProgressBar value={proteinRate} max={100} tone="bg-amber-500" /><p className="mt-1 text-xs text-muted-foreground">目标 {targets.protein} g / 日 · {nutritionWeek.length} 天</p></div><div className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-md bg-muted/40 p-3"><p className="text-xs text-muted-foreground">7 日平均热量</p><p className="mt-1 font-semibold">{calorieAverage !== undefined ? `${Math.round(calorieAverage)} kcal` : "—"}</p><p className="text-xs text-muted-foreground">目标 {targets.calories} kcal</p></div><div className="rounded-md bg-muted/40 p-3"><p className="text-xs text-muted-foreground">当前碳水日</p><p className="mt-1 font-semibold capitalize">{currentCarbDay}</p><p className="text-xs text-muted-foreground">{state.settings.carbTargets[currentCarbDay].carbs} g 碳水</p></div><div className="rounded-md bg-muted/40 p-3"><p className="text-xs text-muted-foreground">水果达标</p><p className="mt-1 font-semibold">{fruitRate}%</p></div><div className="rounded-md bg-muted/40 p-3"><p className="text-xs text-muted-foreground">蔬菜达标</p><p className="mt-1 font-semibold">{vegetableRate}%</p></div></div><button onClick={() => go("/nutrition")} className="flex items-center text-sm text-primary">查看饮食与采购 <ChevronRight className="ml-1 h-4 w-4" /></button></Panel></Section>
    </div>
    <div className="mt-6 grid gap-6 md:grid-cols-2"><Section title="Recovery" meta="7 日平均、趋势与基线偏差"><Panel><div className="grid grid-cols-2 gap-4"><div className="flex items-center gap-2"><BedDouble className="h-4 w-4 text-blue-400" /><div><p className="text-xs text-muted-foreground">睡眠</p><p className="font-semibold">{sleep !== undefined ? `${sleep.toFixed(1)} h` : "—"}</p><p className="text-[11px] text-muted-foreground">趋势 {signed(trendChange(state.recovery, 7, entry => entry.sleepHours))} · 基线 {signed(sleepBaseline)}</p></div></div><div className="flex items-center gap-2"><HeartPulse className="h-4 w-4 text-rose-500" /><div><p className="text-xs text-muted-foreground">HRV</p><p className="font-semibold">{hrv?.toFixed(1) ?? "—"}</p><p className="text-[11px] text-muted-foreground">趋势 {signed(trendChange(state.recovery, 7, entry => entry.hrv))} · 基线 {signed(hrvBaseline)}</p></div></div><div className="flex items-center gap-2"><Timer className="h-4 w-4 text-emerald-500" /><div><p className="text-xs text-muted-foreground">静息心率</p><p className="font-semibold">{restingHr !== undefined ? `${restingHr.toFixed(1)} bpm` : "—"}</p><p className="text-[11px] text-muted-foreground">趋势 {signed(trendChange(state.recovery, 7, entry => entry.restingHr))} · 基线 {signed(restingHrBaseline)}</p></div></div><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-violet-500" /><div><p className="text-xs text-muted-foreground">WHOOP Recovery</p><p className="font-semibold">{whoopRecovery?.toFixed(1) ?? "—"}</p><p className="text-[11px] text-muted-foreground">趋势 {signed(trendChange(state.recovery, 7, entry => entry.whoopRecovery))} · 基线 {signed(whoopBaseline)}</p></div></div></div><TrendChart data={recoveryChart} lines={[{ dataKey: "sleep", color: "var(--chart-1)", name: "睡眠 h" }, { dataKey: "hrv", color: "var(--chart-2)", name: "HRV" }, { dataKey: "whoop", color: "var(--chart-4)", name: "Recovery" }]} /></Panel></Section>
      <Section title="Performance" meta={<button onClick={() => go("/settings")} className="text-primary">编辑基准</button>}><Panel>{benchmarkRows.map(row => <div key={row.key} className="flex items-center gap-3 border-b border-border/50 py-3 last:border-0"><Dumbbell className="h-4 w-4 text-primary" /><div className="min-w-0 flex-1"><p className="text-sm font-medium">{row.label}</p><p className="text-xs text-muted-foreground">当前最佳 {row.observed !== undefined ? `${row.observed}${row.key === "longestFreestyleM" ? " m" : " kg"}` : "—"}</p></div><span className="text-sm font-semibold">{row.target !== undefined ? `${row.target}${row.key === "longestFreestyleM" ? " m" : " kg"}` : "未设置"}</span></div>)}<p className="mt-3 text-xs text-muted-foreground">基准仅用于比较，不会自动修改训练计划。</p></Panel></Section></div>
    <Section title="Quick access" meta="保持低摩擦"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><button onClick={() => go("/log")} className="rounded-lg border border-border/70 bg-card p-4 text-left hover:border-primary/50"><Activity className="h-5 w-5 text-primary" /><p className="mt-3 text-sm font-medium">今日记录</p><p className="mt-1 text-xs text-muted-foreground">体重、训练、恢复</p></button><button onClick={() => go("/nutrition")} className="rounded-lg border border-border/70 bg-card p-4 text-left hover:border-primary/50"><Utensils className="h-5 w-5 text-amber-500" /><p className="mt-3 text-sm font-medium">饮食与购物</p><p className="mt-1 text-xs text-muted-foreground">模板、计划、清单</p></button><button onClick={() => go("/history")} className="rounded-lg border border-border/70 bg-card p-4 text-left hover:border-primary/50"><Waves className="h-5 w-5 text-blue-400" /><p className="mt-3 text-sm font-medium">趋势历史</p><p className="mt-1 text-xs text-muted-foreground">滚动平均与表现</p></button><button onClick={() => go("/review")} className="rounded-lg border border-border/70 bg-card p-4 text-left hover:border-primary/50"><CalendarDays className="h-5 w-5 text-emerald-500" /><p className="mt-3 text-sm font-medium">Review</p><p className="mt-1 text-xs text-muted-foreground">周报与 AI 导出</p></button></div></Section>
  </div>;
}
