import { Activity, BedDouble, CalendarDays, ChevronRight, Dumbbell, Scale, Timer, Utensils, Waves } from "lucide-react";
import { useLocation } from "wouter";
import { PageHeader, Section, Metric, Panel, ProgressBar } from "@/components/os-ui";
import { PHASES, average, daysBetween, formatDate, movingAverage, startOfWeek, useFitnessStore } from "@/lib/localStore";
import { DEFAULT_WEEKLY_SCHEDULE } from "@shared/trainingPlan";

export default function Dashboard() {
  const { state } = useFitnessStore(); const [, go] = useLocation();
  const today = formatDate(); const week = startOfWeek();
  const phase = PHASES[state.settings.phase]; const weekNumber = Math.min(phase.weeks, Math.floor(daysBetween(state.settings.phaseStarted) / 7) + 1);
  const weekActivities = state.activities.filter(a => a.date >= week && a.date <= today && a.completed);
  const strength = weekActivities.filter(a => a.type === "strength").length; const swimming = weekActivities.filter(a => a.type === "swimming"); const tennis = weekActivities.filter(a => a.type === "tennis");
  const weeklySchedule = state.weeklySchedule?.length ? state.weeklySchedule : DEFAULT_WEEKLY_SCHEDULE;
  const strengthTarget = weeklySchedule.filter(item => item.type === "strength").length;
  const strengthRate = strengthTarget ? Math.min(100, Math.round(strength / strengthTarget * 100)) : 0;
  const bodyAvg = movingAverage(state.body, 7); const latest = [...state.body].sort((a,b) => b.date.localeCompare(a.date))[0];
  const nutritionWeek = state.nutrition.filter(n => n.date >= week && n.date <= today); const proteinRate = nutritionWeek.length ? Math.round(nutritionWeek.filter(n => (n.protein ?? 0) >= state.settings.nutritionTargets.protein).length / nutritionWeek.length * 100) : 0;
  const sleep = average(state.recovery.filter(r => r.date >= week).map(r => r.sleepHours));
  return <div className="pb-10"><PageHeader eyebrow="Personal Fitness OS" title="Dashboard" description={`${today} · ${phase.label} · 第 ${weekNumber} / ${phase.weeks} 周`} action={<button onClick={() => go("/log")} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">+ 快速记录</button>} />
    <Panel className="mb-6 flex items-center justify-between gap-4 border-primary/30 bg-primary/5"><div><p className="text-xs font-medium text-primary">CURRENT PHASE</p><p className="mt-1 text-lg font-semibold">{phase.label}</p><p className="text-sm text-muted-foreground">{phase.subtitle}</p></div><div className="text-right"><p className="text-3xl font-semibold">{weekNumber}<span className="text-base text-muted-foreground">/{phase.weeks}</span></p><p className="text-xs text-muted-foreground">周进度</p></div></Panel>
    <Section title="Body" meta="趋势优先，不对单日数据过度反应"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="当前体重" value={latest?.weight ? `${latest.weight.toFixed(1)} kg` : "—"} detail={latest?.date ?? "尚未记录"} /><Metric label="7 日平均" value={bodyAvg ? `${bodyAvg.toFixed(1)} kg` : "—"} detail="移动平均" /><Metric label="腰围" value={latest?.waist ? `${latest.waist.toFixed(1)} cm` : "—"} /><Metric label="体脂估计" value={latest?.bodyFat ? `${latest.bodyFat.toFixed(1)}%` : "—"} detail="估计值" /></div></Section>
    <div className="mt-6 grid gap-6 md:grid-cols-2"><Section title="Training" meta={strengthTarget ? `${strength} / ${strengthTarget} 次力量` : "未安排力量训练"}><Panel><div className="grid grid-cols-2 gap-4"><div><p className="text-xs text-muted-foreground">游泳</p><p className="mt-1 text-xl font-semibold">{swimming.length} <span className="text-sm font-normal text-muted-foreground">次</span></p><p className="text-xs text-muted-foreground">{(swimming.reduce((s,a) => s + (a.distanceM ?? 0), 0) / 1000).toFixed(1)} km</p></div><div><p className="text-xs text-muted-foreground">网球</p><p className="mt-1 text-xl font-semibold">{tennis.length} <span className="text-sm font-normal text-muted-foreground">次</span></p><p className="text-xs text-muted-foreground">{Math.round(tennis.reduce((s,a) => s + a.durationMin, 0) / 60 * 10) / 10} 小时</p></div></div><div className="mt-4"><div className="mb-2 flex justify-between text-xs"><span>本周力量完成度</span><span>{strengthRate}%</span></div><ProgressBar value={strength} max={Math.max(strengthTarget, 1)} /></div><button onClick={() => go("/plan")} className="mt-4 flex items-center text-sm text-primary">查看本周计划 <ChevronRight className="ml-1 h-4 w-4" /></button></Panel></Section>
      <Section title="Nutrition & Recovery"><div className="space-y-3"><Panel><div className="flex items-center gap-3"><Utensils className="h-5 w-5 text-amber-500" /><div className="flex-1"><div className="flex justify-between"><p className="text-sm font-medium">蛋白质达标</p><p className="text-sm font-semibold">{proteinRate}%</p></div><ProgressBar value={proteinRate} max={100} tone="bg-amber-500" /></div></div><p className="mt-2 text-xs text-muted-foreground">目标 {state.settings.nutritionTargets.protein} g / 日 · 本周 {nutritionWeek.length} 天</p></Panel><Panel><div className="grid grid-cols-2 gap-4"><div className="flex items-center gap-2"><BedDouble className="h-4 w-4 text-blue-400" /><div><p className="text-xs text-muted-foreground">平均睡眠</p><p className="font-semibold">{sleep ? `${sleep.toFixed(1)} h` : "—"}</p></div></div><div className="flex items-center gap-2"><Timer className="h-4 w-4 text-emerald-500" /><div><p className="text-xs text-muted-foreground">训练时长</p><p className="font-semibold">{weekActivities.reduce((s,a) => s + a.durationMin, 0)} min</p></div></div></div></Panel></div></Section></div>
    <Section title="Quick access" meta="保持低摩擦"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><button onClick={() => go("/log")} className="rounded-lg border border-border/70 bg-card p-4 text-left hover:border-primary/50"><Activity className="h-5 w-5 text-primary" /><p className="mt-3 text-sm font-medium">今日记录</p><p className="mt-1 text-xs text-muted-foreground">体重、训练、恢复</p></button><button onClick={() => go("/nutrition")} className="rounded-lg border border-border/70 bg-card p-4 text-left hover:border-primary/50"><Utensils className="h-5 w-5 text-amber-500" /><p className="mt-3 text-sm font-medium">饮食与购物</p><p className="mt-1 text-xs text-muted-foreground">模板、计划、清单</p></button><button onClick={() => go("/history")} className="rounded-lg border border-border/70 bg-card p-4 text-left hover:border-primary/50"><Waves className="h-5 w-5 text-blue-400" /><p className="mt-3 text-sm font-medium">趋势历史</p><p className="mt-1 text-xs text-muted-foreground">滚动平均与表现</p></button><button onClick={() => go("/review")} className="rounded-lg border border-border/70 bg-card p-4 text-left hover:border-primary/50"><CalendarDays className="h-5 w-5 text-emerald-500" /><p className="mt-3 text-sm font-medium">Review</p><p className="mt-1 text-xs text-muted-foreground">周报与 AI 导出</p></button></div></Section>
  </div>;
}
