import { FormEvent, useEffect, useState } from "react";
import { Activity, Check, Plus, Save, Trash2 } from "lucide-react";
import { PageHeader, Panel, Section } from "@/components/os-ui";
import { uid, useFitnessStore, type ActivityEntry, type BodyEntry, type RecoveryEntry, type NutritionEntry } from "@/lib/localStore";

const today = () => new Date().toISOString().slice(0, 10);
const Field = ({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) => <label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">{label}</span><input {...props} className="w-full rounded-md border border-input bg-background px-3 py-2" /></label>;

export default function Log() {
  const { state, add, update, remove } = useFitnessStore(); const [date, setDate] = useState(today()); const [saved, setSaved] = useState(false);
  const body = state.body.find(x => x.date === date); const recovery = state.recovery.find(x => x.date === date); const activities = state.activities.filter(x => x.date === date); const nutrition = state.nutrition.find(x => x.date === date);
  const [bodyForm, setBodyForm] = useState({ weight: body?.weight?.toString() ?? "", waist: body?.waist?.toString() ?? "", bodyFat: body?.bodyFat?.toString() ?? "" });
  const [recoveryForm, setRecoveryForm] = useState({ sleepHours: recovery?.sleepHours?.toString() ?? "", hrv: recovery?.hrv?.toString() ?? "", restingHr: recovery?.restingHr?.toString() ?? "", whoopRecovery: recovery?.whoopRecovery?.toString() ?? "", whoopStrain: recovery?.whoopStrain?.toString() ?? "", vo2max: recovery?.vo2max?.toString() ?? "", fatigue: recovery?.fatigue?.toString() ?? "", soreness: recovery?.soreness?.toString() ?? "", motivation: recovery?.motivation?.toString() ?? "", hunger: recovery?.hunger?.toString() ?? "" });
  const [activityForm, setActivityForm] = useState({ type: "strength" as ActivityEntry["type"], title: "力量训练", durationMin: "45", rpe: "", distanceM: "", freestyleM: "", longestFreestyleM: "" });
  const [nutritionForm, setNutritionForm] = useState({ calories: nutrition?.calories?.toString() ?? "", protein: nutrition?.protein?.toString() ?? "", carbs: nutrition?.carbs?.toString() ?? "", fat: nutrition?.fat?.toString() ?? "", fruitServings: nutrition?.fruitServings?.toString() ?? "2", vegetableServings: nutrition?.vegetableServings?.toString() ?? "4", carbDay: nutrition?.carbDay ?? "medium" as NutritionEntry["carbDay"] });
  useEffect(() => {
    setBodyForm({ weight: body?.weight?.toString() ?? "", waist: body?.waist?.toString() ?? "", bodyFat: body?.bodyFat?.toString() ?? "" });
    setRecoveryForm({ sleepHours: recovery?.sleepHours?.toString() ?? "", hrv: recovery?.hrv?.toString() ?? "", restingHr: recovery?.restingHr?.toString() ?? "", whoopRecovery: recovery?.whoopRecovery?.toString() ?? "", whoopStrain: recovery?.whoopStrain?.toString() ?? "", vo2max: recovery?.vo2max?.toString() ?? "", fatigue: recovery?.fatigue?.toString() ?? "", soreness: recovery?.soreness?.toString() ?? "", motivation: recovery?.motivation?.toString() ?? "", hunger: recovery?.hunger?.toString() ?? "" });
    setNutritionForm({ calories: nutrition?.calories?.toString() ?? "", protein: nutrition?.protein?.toString() ?? "", carbs: nutrition?.carbs?.toString() ?? "", fat: nutrition?.fat?.toString() ?? "", fruitServings: nutrition?.fruitServings?.toString() ?? "2", vegetableServings: nutrition?.vegetableServings?.toString() ?? "4", carbDay: nutrition?.carbDay ?? "medium" });
  }, [date]);
  const save = (event: FormEvent) => { event.preventDefault(); const n = (value: string) => value ? Number(value) : undefined; update(s => ({ ...s, body: [...s.body.filter(x => x.date !== date), { id: body?.id ?? uid("body"), date, weight: n(bodyForm.weight), waist: n(bodyForm.waist), bodyFat: n(bodyForm.bodyFat) } as BodyEntry], recovery: [...s.recovery.filter(x => x.date !== date), { id: recovery?.id ?? uid("recovery"), date, sleepHours: n(recoveryForm.sleepHours), hrv: n(recoveryForm.hrv), restingHr: n(recoveryForm.restingHr), whoopRecovery: n(recoveryForm.whoopRecovery), whoopStrain: n(recoveryForm.whoopStrain), vo2max: n(recoveryForm.vo2max), fatigue: n(recoveryForm.fatigue), soreness: n(recoveryForm.soreness), motivation: n(recoveryForm.motivation), hunger: n(recoveryForm.hunger) } as RecoveryEntry], nutrition: [...s.nutrition.filter(x => x.date !== date), { id: nutrition?.id ?? uid("nutrition"), date, ...Object.fromEntries(Object.entries(nutritionForm).map(([k,v]) => [k, k === "carbDay" ? v : n(v as string)])) } as NutritionEntry] })); setSaved(true); setTimeout(() => setSaved(false), 1800); };
  const addActivity = () => { add("activities", { id: uid("activity"), date, type: activityForm.type, title: activityForm.title, durationMin: Number(activityForm.durationMin) || 0, rpe: activityForm.rpe ? Number(activityForm.rpe) : undefined, distanceM: activityForm.distanceM ? Number(activityForm.distanceM) : undefined, freestyleM: activityForm.freestyleM ? Number(activityForm.freestyleM) : undefined, longestFreestyleM: activityForm.longestFreestyleM ? Number(activityForm.longestFreestyleM) : undefined, completed: true } as ActivityEntry); };
  return <div className="pb-10"><PageHeader eyebrow="Log" title="每日记录" description="把今天的关键信息一次记下。默认值会沿用上次输入。" action={<label className="flex items-center gap-2 text-sm"><span className="text-muted-foreground">日期</span><input type="date" value={date} onChange={e => setDate(e.target.value)} className="rounded-md border border-input bg-background px-3 py-2" /></label>} />
    <form onSubmit={save} className="space-y-6"><Section title="Body"><Panel><div className="grid gap-3 sm:grid-cols-3"><Field label="晨起体重 (kg)" type="number" step="0.1" value={bodyForm.weight} onChange={e => setBodyForm({ ...bodyForm, weight: e.target.value })} /><Field label="腰围 (cm)" type="number" step="0.1" value={bodyForm.waist} onChange={e => setBodyForm({ ...bodyForm, waist: e.target.value })} /><Field label="体脂估计 (%)" type="number" step="0.1" value={bodyForm.bodyFat} onChange={e => setBodyForm({ ...bodyForm, bodyFat: e.target.value })} /></div></Panel></Section>
      <Section title="Training" meta={`${activities.length} 个 session`}><Panel><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select value={activityForm.type} onChange={e => setActivityForm({ ...activityForm, type: e.target.value as ActivityEntry["type"] })} className="rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="strength">力量</option><option value="swimming">游泳</option><option value="tennis">网球</option><option value="boxing">拳击</option><option value="other">其他</option></select><input value={activityForm.title} onChange={e => setActivityForm({ ...activityForm, title: e.target.value })} className="rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="Session 名称" /><input value={activityForm.durationMin} onChange={e => setActivityForm({ ...activityForm, durationMin: e.target.value })} className="rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="分钟" type="number" /><input value={activityForm.rpe} onChange={e => setActivityForm({ ...activityForm, rpe: e.target.value })} className="rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="RPE" type="number" min="1" max="10" />{activityForm.type === "swimming" && <><input value={activityForm.distanceM} onChange={e => setActivityForm({ ...activityForm, distanceM: e.target.value })} className="rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="总距离 (m)" type="number" /><input value={activityForm.freestyleM} onChange={e => setActivityForm({ ...activityForm, freestyleM: e.target.value })} className="rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="自由泳 (m)" type="number" /><input value={activityForm.longestFreestyleM} onChange={e => setActivityForm({ ...activityForm, longestFreestyleM: e.target.value })} className="rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="连续自由泳 (m)" type="number" /></>}<button type="button" onClick={addActivity} className="flex items-center justify-center rounded-md bg-secondary px-3 py-2 text-sm"><Plus className="mr-1 h-4 w-4" />添加</button></div><div className="mt-3 divide-y divide-border/50">{activities.map(a => <div key={a.id} className="flex items-center py-3 text-sm"><Activity className="mr-3 h-4 w-4 text-primary" /><span className="flex-1">{a.title}</span><span className="mr-4 text-muted-foreground">{a.durationMin} min {a.rpe ? `· RPE ${a.rpe}` : ""}{a.distanceM ? ` · ${a.distanceM} m` : ""}</span><button type="button" onClick={() => remove("activities", a.id)} aria-label="删除训练"><Trash2 className="h-4 w-4 text-muted-foreground" /></button></div>)}</div></Panel></Section>
      <Section title="Nutrition"><Panel><div className="grid gap-3 sm:grid-cols-4"><Field label="热量 (kcal)" type="number" value={nutritionForm.calories} onChange={e => setNutritionForm({ ...nutritionForm, calories: e.target.value })} /><Field label="蛋白质 (g)" type="number" value={nutritionForm.protein} onChange={e => setNutritionForm({ ...nutritionForm, protein: e.target.value })} /><Field label="碳水 (g)" type="number" value={nutritionForm.carbs} onChange={e => setNutritionForm({ ...nutritionForm, carbs: e.target.value })} /><Field label="脂肪 (g)" type="number" value={nutritionForm.fat} onChange={e => setNutritionForm({ ...nutritionForm, fat: e.target.value })} /><Field label="水果 servings" type="number" value={nutritionForm.fruitServings} onChange={e => setNutritionForm({ ...nutritionForm, fruitServings: e.target.value })} /><Field label="蔬菜 servings" type="number" value={nutritionForm.vegetableServings} onChange={e => setNutritionForm({ ...nutritionForm, vegetableServings: e.target.value })} /><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">碳水日</span><select value={nutritionForm.carbDay} onChange={e => setNutritionForm({ ...nutritionForm, carbDay: e.target.value as NutritionEntry["carbDay"] })} className="w-full rounded-md border border-input bg-background px-3 py-2"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div></Panel></Section>
      <Section title="Recovery"><Panel><div className="grid gap-3 sm:grid-cols-4"><Field label="睡眠 (h)" type="number" step="0.1" value={recoveryForm.sleepHours} onChange={e => setRecoveryForm({ ...recoveryForm, sleepHours: e.target.value })} /><Field label="HRV" type="number" value={recoveryForm.hrv} onChange={e => setRecoveryForm({ ...recoveryForm, hrv: e.target.value })} /><Field label="静息心率" type="number" value={recoveryForm.restingHr} onChange={e => setRecoveryForm({ ...recoveryForm, restingHr: e.target.value })} /><Field label="WHOOP Recovery" type="number" value={recoveryForm.whoopRecovery} onChange={e => setRecoveryForm({ ...recoveryForm, whoopRecovery: e.target.value })} /><Field label="WHOOP Strain" type="number" value={recoveryForm.whoopStrain} onChange={e => setRecoveryForm({ ...recoveryForm, whoopStrain: e.target.value })} /><Field label="VO2max 估计" type="number" step="0.1" value={recoveryForm.vo2max} onChange={e => setRecoveryForm({ ...recoveryForm, vo2max: e.target.value })} /><Field label="疲劳 1–5" type="number" min="1" max="5" value={recoveryForm.fatigue} onChange={e => setRecoveryForm({ ...recoveryForm, fatigue: e.target.value })} /><Field label="酸痛 1–5" type="number" min="1" max="5" value={recoveryForm.soreness} onChange={e => setRecoveryForm({ ...recoveryForm, soreness: e.target.value })} /><Field label="动力 1–5" type="number" min="1" max="5" value={recoveryForm.motivation} onChange={e => setRecoveryForm({ ...recoveryForm, motivation: e.target.value })} /><Field label="饥饿 1–5" type="number" min="1" max="5" value={recoveryForm.hunger} onChange={e => setRecoveryForm({ ...recoveryForm, hunger: e.target.value })} /></div></Panel></Section>
      <div className="sticky bottom-4 flex justify-end"><button type="submit" className="flex items-center gap-2 rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground shadow-lg"><Save className="h-4 w-4" />{saved ? "已保存" : "保存今日记录"}{saved && <Check className="h-4 w-4" />}</button></div></form>
  </div>;
}
