import { useMemo, useState } from "react";
import { Check, Pencil, Plus, Save, ShoppingCart, Trash2, Utensils } from "lucide-react";
import { useLocation } from "wouter";
import { CheckRow, Empty, PageHeader, Panel, ProgressBar, Section } from "@/components/os-ui";
import { formatDate, uid, useFitnessStore, type FoodItem, type GroceryItem, type StandardHomeDiet } from "@/lib/localStore";
import type { IngredientDetail, MealTemplate } from "@shared/mealTemplates";

const foodDefaults: GroceryItem[] = [
  { id: uid("grocery"), category: "蛋白质", name: "鸡胸肉", required: 2100, unit: "g", purchase: "3 × 1 kg 包", checked: false },
  { id: uid("grocery"), category: "蛋白质", name: "鸡蛋", required: 21, unit: "个", purchase: "2 × 12 个装", checked: false },
  { id: uid("grocery"), category: "蛋白质", name: "牛奶", required: 3500, unit: "ml", purchase: "4 × 1 L 盒", checked: false },
  { id: uid("grocery"), category: "蛋白质", name: "三文鱼（替换鸡肉）", required: 500, unit: "g", purchase: "1 × 500 g 包", checked: false },
  { id: uid("grocery"), category: "碳水", name: "白米", required: 1400, unit: "g 生重", purchase: "1 × 2 kg 袋", checked: false },
  { id: uid("grocery"), category: "水果", name: "香蕉 / 苹果", required: 14, unit: "份", purchase: "约 14 份", checked: false },
  { id: uid("grocery"), category: "蔬菜", name: "混合蔬菜", required: 2800, unit: "g", purchase: "按喜好采购", checked: false },
];

const numericIngredientFields = new Set(["kcal", "protein", "carbs", "fat"]);
const scaleAmount = (amount: string, scale: number) => amount.replace(/^(\d+(?:\.\d+)?)/, (_, value: string) => String(Math.round(Number(value) * scale * 10) / 10));
const scaled = (value: number, scale: number) => Math.round(value * scale);

function IngredientEditor({ ingredient, onChange }: { ingredient: IngredientDetail; onChange: (field: keyof IngredientDetail, value: string) => void }) {
  return <div className="grid gap-2 rounded-md border border-border/60 p-2 sm:grid-cols-[1.3fr_1fr_repeat(4,70px)]"><input aria-label="食材名称" value={ingredient.name} onChange={e => onChange("name", e.target.value)} className="rounded border border-input bg-background px-2 py-1 text-sm" /><input aria-label="食材数量" value={ingredient.amount} onChange={e => onChange("amount", e.target.value)} className="rounded border border-input bg-background px-2 py-1 text-sm" />{(["kcal", "protein", "carbs", "fat"] as const).map(field => <input key={field} aria-label={field} type="number" value={ingredient[field]} onChange={e => onChange(field, e.target.value)} className="rounded border border-input bg-background px-2 py-1 text-xs" />)}</div>;
}

export default function Nutrition() {
  const { state, update } = useFitnessStore();
  const [, go] = useLocation();
  const [tab, setTab] = useState<"today" | "templates" | "foods" | "weekly" | "grocery">("today");
  const [templateScales, setTemplateScales] = useState<Record<string, number>>({});
  const [editingTemplateId, setEditingTemplateId] = useState<string | null>(null);
  const today = formatDate();
  const entry = state.nutrition.find(n => n.date === today);
  const target = state.settings.nutritionTargets;
  const items = state.grocery.length ? state.grocery : foodDefaults;
  const grouped = useMemo(() => items.reduce<Record<string, GroceryItem[]>>((acc, item) => { (acc[item.category] ??= []).push(item); return acc; }, {}), [items]);
  const updateHomeDiet = (key: keyof StandardHomeDiet, value: string) => update(current => ({ ...current, standardHomeDiet: { ...current.standardHomeDiet, [key]: Number(value) || 0 } }));
  const setCarbDay = (carbDay: "low" | "medium" | "high") => update(current => {
    const existing = current.nutrition.find(item => item.date === today);
    const next = { ...(existing ?? { id: uid("nutrition"), date: today, homeMeals: 0 }), carbDay };
    return { ...current, nutrition: [...current.nutrition.filter(item => item.date !== today), next] };
  });
  const updateFood = (id: string, patch: Partial<FoodItem>) => update(current => ({ ...current, foods: current.foods.map(food => food.id === id ? { ...food, ...patch } : food) }));
  const addFood = () => update(current => ({ ...current, foods: [...current.foods, { id: uid("food"), name: "新食物", category: "其他", nutritionUnit: "100 g", shoppingUnit: "按包装", caloriesPerUnit: 0, proteinPerUnit: 0, carbsPerUnit: 0, fatPerUnit: 0 }] }));
  const removeFood = (id: string) => update(current => ({ ...current, foods: current.foods.filter(food => food.id !== id) }));
  const updateTemplateIngredient = (templateId: string, key: "rice" | "meat" | "greenVeg" | "hardyVeg", index: number | undefined, field: keyof IngredientDetail, value: string) => update(current => ({ ...current, mealTemplates: current.mealTemplates.map(template => {
    if (template.id !== templateId) return template;
    const numeric = numericIngredientFields.has(field);
    const parsed = numeric ? Number(value) || 0 : value;
    if (key === "hardyVeg") return { ...template, hardyVeg: template.hardyVeg.map((ingredient, ingredientIndex) => ingredientIndex === index ? { ...ingredient, [field]: parsed } : ingredient) };
    return { ...template, [key]: { ...template[key], [field]: parsed } };
  }) }));
  const generate = () => update(current => ({ ...current, grocery: foodDefaults.map(item => ({ ...item, id: uid("grocery") })) }));
  const updateScale = (template: MealTemplate, value: string) => setTemplateScales(current => ({ ...current, [template.id]: Number(value) || 1 }));

  return <div className="pb-10"><PageHeader eyebrow="Nutrition" title="饮食与购物" description="把可编辑目标、食物和餐模板变成低摩擦的每日选择。" />
    <div className="mb-6 flex gap-1 overflow-x-auto border-b border-border">{(["today", "templates", "foods", "weekly", "grocery"] as const).map(item => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap border-b-2 px-3 py-2 text-sm ${tab === item ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>{item === "today" ? "Today" : item === "templates" ? "Meal Templates" : item === "foods" ? "Foods" : item === "weekly" ? "Weekly Plan" : "Grocery"}</button>)}</div>
    {tab === "today" && <div className="space-y-6"><Section title="Today's targets" meta={entry ? `已记录 · ${entry.carbDay} carb day` : "尚未记录"}><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Panel><p className="text-xs text-muted-foreground">热量</p><p className="mt-1 text-xl font-semibold">{entry?.calories ?? 0} <span className="text-xs font-normal">/ {target.calories}</span></p><ProgressBar value={entry?.calories ?? 0} max={target.calories} tone="bg-orange-500" /></Panel><Panel><p className="text-xs text-muted-foreground">蛋白质</p><p className="mt-1 text-xl font-semibold">{entry?.protein ?? 0} <span className="text-xs font-normal">/ {target.protein} g</span></p><ProgressBar value={entry?.protein ?? 0} max={target.protein} /></Panel><Panel><p className="text-xs text-muted-foreground">水果</p><p className="mt-1 text-xl font-semibold">{entry?.fruitServings ?? 0} <span className="text-xs font-normal">/ {target.fruit}</span></p><ProgressBar value={entry?.fruitServings ?? 0} max={target.fruit} tone="bg-emerald-500" /></Panel><Panel><p className="text-xs text-muted-foreground">蔬菜</p><p className="mt-1 text-xl font-semibold">{entry?.vegetableServings ?? 0} <span className="text-xs font-normal">/ {target.vegetables}</span></p><ProgressBar value={entry?.vegetableServings ?? 0} max={target.vegetables} tone="bg-emerald-500" /></Panel></div></Section>
      <Section title="Carb-day classification" meta="数值可在设置中调整"><Panel><div className="flex flex-wrap gap-2">{(["low", "medium", "high"] as const).map(carbDay => <button key={carbDay} onClick={() => setCarbDay(carbDay)} className={`rounded-md border px-4 py-2 text-sm ${entry?.carbDay === carbDay ? "border-primary bg-primary/10 text-primary" : "border-border"}`}>{carbDay === "low" ? "Low · 休息 / 恢复" : carbDay === "medium" ? "Medium · 力量 / 中等游泳" : "High · 长网球 / 高强度"}</button>)}</div><button onClick={() => go("/settings")} className="mt-3 flex items-center gap-1 text-sm text-primary"><Pencil className="h-3.5 w-3.5" />编辑碳水和热量目标</button></Panel></Section>
      <Section title="Standard Home Diet" meta="数量可编辑，鸡肉默认每周约两天替换为鱼"><Panel><div className="flex items-start gap-3"><Utensils className="mt-0.5 h-5 w-5 text-amber-500" /><div className="flex-1"><p className="font-medium">Standard Home Diet</p><p className="mt-1 text-sm text-muted-foreground">以生重和可执行单位记录，米饭内部按克计算；第一次使用前请在 Settings 填写电饭煲杯实际生米重量。</p><div className="mt-4 grid gap-3 sm:grid-cols-2 md:grid-cols-4">{([ ["chickenGrams", "鸡胸肉 (g/日)"], ["eggs", "鸡蛋 (个/日)"], ["milkMl", "牛奶 (ml/日)"], ["wheyScoops", "乳清 (勺/日)"], ["riceGrams", "白米 (g/日)"], ["vegetableServings", "蔬菜 (份/日)"], ["fruitServings", "水果 (份/日)"], ["fishSubstitutionDays", "鱼类替换 (天/周)"] ] as const).map(([key, label]) => <label key={key} className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">{label}</span><input type="number" min="0" value={state.standardHomeDiet[key]} onChange={e => updateHomeDiet(key, e.target.value)} className="w-full rounded-md border border-input bg-background px-3 py-2" /></label>)}</div></div></div></Panel></Section></div>}
    {tab === "templates" && <Section title="Meal Templates" meta="可编辑食材并按份数缩放营养估算"><div className="space-y-3">{state.mealTemplates.map(template => { const scale = templateScales[template.id] ?? 1; const editing = editingTemplateId === template.id; const ingredients: Array<{ key: "rice" | "meat" | "greenVeg" | "hardyVeg"; index?: number; ingredient: IngredientDetail; label: string }> = [{ key: "rice", ingredient: template.rice, label: "米饭" }, ...template.hardyVeg.map((ingredient, index) => ({ key: "hardyVeg" as const, index, ingredient, label: `蔬菜 ${index + 1}` })), { key: "meat", ingredient: template.meat, label: "蛋白质" }, { key: "greenVeg", ingredient: template.greenVeg, label: "绿叶菜" }]; return <Panel key={template.id}><div className="flex flex-wrap items-start gap-3"><span className="text-2xl">{template.emoji}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{template.label}</p><p className="mt-1 text-xs text-muted-foreground">{template.dayType === "training" ? "训练日" : "非训练日"} · {scaled(template.dayTotalKcal, scale)} kcal · P {scaled(template.macros.protein, scale)} g · C {scaled(template.macros.carbs, scale)} g · F {scaled(template.macros.fat, scale)} g</p></div><div className="flex items-center gap-2"><label className="text-xs text-muted-foreground">份数 <select value={scale} onChange={e => updateScale(template, e.target.value)} className="ml-1 rounded border border-input bg-background px-2 py-1 text-sm"><option value="0.5">0.5</option><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label><button type="button" onClick={() => setEditingTemplateId(editing ? null : template.id)} className="flex items-center gap-1 text-sm text-primary">{editing ? <Save className="h-4 w-4" /> : <Pencil className="h-4 w-4" />}{editing ? "完成" : "编辑"}</button></div></div><div className="mt-3 space-y-2">{ingredients.map(({ key, index, ingredient, label }) => editing ? <IngredientEditor key={`${key}-${index ?? 0}`} ingredient={ingredient} onChange={(field, value) => updateTemplateIngredient(template.id, key, index, field, value)} /> : <div key={`${key}-${index ?? 0}`} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="text-muted-foreground">{label} · {ingredient.name}</span><span>{scaleAmount(ingredient.amount, scale)} · {scaled(ingredient.kcal, scale)} kcal</span></div>)}</div><p className="mt-3 text-xs text-muted-foreground">{template.tips}</p></div></div></Panel>})}</div></Section>}
    {tab === "foods" && <Section title="Foods" meta="营养单位与购物单位分开保存"><Panel><div className="mb-3 flex items-center justify-between"><p className="text-sm text-muted-foreground">修改目录会作为后续餐模板和购物计算的基础。</p><button onClick={addFood} className="flex items-center gap-1 text-sm text-primary"><Plus className="h-4 w-4" />添加食物</button></div>{state.foods.length ? <div className="space-y-2">{state.foods.map(food => <div key={food.id} className="grid gap-2 rounded-md border border-border/60 p-3 md:grid-cols-[1.3fr_90px_110px_110px_repeat(4,70px)_32px]"><input aria-label="食物名称" value={food.name} onChange={e => updateFood(food.id, { name: e.target.value })} className="rounded border border-input bg-background px-2 py-1.5 text-sm" /><input aria-label="分类" value={food.category} onChange={e => updateFood(food.id, { category: e.target.value })} className="rounded border border-input bg-background px-2 py-1.5 text-sm" /><input aria-label="营养单位" value={food.nutritionUnit} onChange={e => updateFood(food.id, { nutritionUnit: e.target.value })} className="rounded border border-input bg-background px-2 py-1.5 text-xs" /><input aria-label="购物单位" value={food.shoppingUnit} onChange={e => updateFood(food.id, { shoppingUnit: e.target.value })} className="rounded border border-input bg-background px-2 py-1.5 text-xs" />{(["caloriesPerUnit", "proteinPerUnit", "carbsPerUnit", "fatPerUnit"] as const).map(field => <input key={field} aria-label={field} type="number" value={food[field]} onChange={e => updateFood(food.id, { [field]: Number(e.target.value) || 0 })} className="rounded border border-input bg-background px-1 py-1.5 text-xs" />)}<button type="button" aria-label={`删除 ${food.name}`} onClick={() => removeFood(food.id)} className="flex items-center justify-center text-muted-foreground"><Trash2 className="h-4 w-4" /></button></div>)}</div> : <Empty><p className="text-sm">还没有食物</p></Empty>}</Panel></Section>}
    {tab === "weekly" && <Section title="Weekly meal planning" meta="每周计划和 Grocery 计算将在 P4 完成"><Panel><div className="grid gap-3 sm:grid-cols-3"><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">计划周期</span><input value="7" readOnly className="w-full rounded-md border border-input bg-background px-3 py-2" /></label><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">预计居家餐</span><input value="14" readOnly className="w-full rounded-md border border-input bg-background px-3 py-2" /></label><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">预计社交餐</span><input defaultValue="3" className="w-full rounded-md border border-input bg-background px-3 py-2" /></label></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-md border border-border/60 p-3"><p className="font-medium">Low</p><p className="mt-1 text-xs text-muted-foreground">休息、恢复或非常轻松的游泳 · {state.settings.carbTargets.low.carbs} g 碳水</p></div><div className="rounded-md border border-border/60 p-3"><p className="font-medium">Medium</p><p className="mt-1 text-xs text-muted-foreground">力量训练或中等游泳 · {state.settings.carbTargets.medium.carbs} g 碳水</p></div><div className="rounded-md border border-border/60 p-3"><p className="font-medium">High</p><p className="mt-1 text-xs text-muted-foreground">长网球、高强度游泳或拳击 · {state.settings.carbTargets.high.carbs} g 碳水</p></div></div><p className="mt-4 text-sm text-muted-foreground">社交餐不是失败记录；P4 会根据居家餐数量和餐模板生成可执行采购量。</p></Panel></Section>}
    {tab === "grocery" && <Section title="Grocery checklist" meta="营养单位与购物单位分开"><div className="mb-3 flex items-center justify-between"><p className="text-sm text-muted-foreground">当前为 P4 前的基础清单，完整周计划计算随后接入。</p><button onClick={generate} className="flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"><ShoppingCart className="h-4 w-4" />生成清单</button></div><Panel>{Object.entries(grouped).map(([category, categoryItems]) => <div key={category} className="mb-5 last:mb-0"><h3 className="mb-1 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{category}</h3>{categoryItems.map(item => <CheckRow key={item.id} checked={item.checked} onChange={() => update(s => ({ ...s, grocery: items.map(current => current.id === item.id ? { ...current, checked: !current.checked } : current) }))}><span className="text-sm">{item.name} <span className="text-muted-foreground">· {item.required} {item.unit} · 购买 {item.purchase}</span></span></CheckRow>)}</div>)}</Panel><button onClick={() => update(s => ({ ...s, groceryHistory: [...s.groceryHistory, { date: today, items }] }))} className="mt-3 flex items-center gap-2 text-sm text-primary"><Check className="h-4 w-4" />完成购物并保存历史</button></Section>}
  </div>;
}
