import { useMemo, useState } from "react";
import { Check, ClipboardList, ShoppingCart, Utensils } from "lucide-react";
import { PageHeader, Panel, Section, ProgressBar, CheckRow } from "@/components/os-ui";
import { formatDate, uid, useFitnessStore, type GroceryItem } from "@/lib/localStore";

const foodDefaults: GroceryItem[] = [
  { id: uid("grocery"), category: "蛋白质", name: "鸡胸肉", required: 2100, unit: "g", purchase: "3 × 1 kg 包", checked: false },
  { id: uid("grocery"), category: "蛋白质", name: "鸡蛋", required: 21, unit: "个", purchase: "2 × 12 个装", checked: false },
  { id: uid("grocery"), category: "蛋白质", name: "牛奶", required: 3500, unit: "ml", purchase: "4 × 1 L 盒", checked: false },
  { id: uid("grocery"), category: "蛋白质", name: "三文鱼（替换鸡肉）", required: 500, unit: "g", purchase: "1 × 500 g 包", checked: false },
  { id: uid("grocery"), category: "碳水", name: "白米", required: 1400, unit: "g 生重", purchase: "1 × 2 kg 袋", checked: false },
  { id: uid("grocery"), category: "水果", name: "香蕉 / 苹果", required: 14, unit: "份", purchase: "约 14 份", checked: false },
  { id: uid("grocery"), category: "蔬菜", name: "混合蔬菜", required: 2800, unit: "g", purchase: "按喜好采购", checked: false },
];

export default function Nutrition() {
  const { state, update } = useFitnessStore(); const [tab, setTab] = useState<"today" | "templates" | "weekly" | "grocery">("today");
  const today = formatDate(); const entry = state.nutrition.find(n => n.date === today); const target = state.settings.nutritionTargets; const items = state.grocery.length ? state.grocery : foodDefaults;
  const grouped = useMemo(() => items.reduce<Record<string, GroceryItem[]>>((acc, item) => { (acc[item.category] ??= []).push(item); return acc; }, {}), [items]);
  const generate = () => update(s => ({ ...s, grocery: foodDefaults.map(i => ({ ...i, id: uid("grocery") })) }));
  return <div className="pb-10"><PageHeader eyebrow="Nutrition" title="饮食与购物" description="模板化重复决策，把目标转成今天能执行的食物和清单。" />
    <div className="mb-6 flex gap-1 overflow-x-auto border-b border-border"><button onClick={() => setTab("today")} className={`whitespace-nowrap border-b-2 px-3 py-2 text-sm ${tab === "today" ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>Today</button><button onClick={() => setTab("templates")} className={`whitespace-nowrap border-b-2 px-3 py-2 text-sm ${tab === "templates" ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>Meal Templates</button><button onClick={() => setTab("weekly")} className={`whitespace-nowrap border-b-2 px-3 py-2 text-sm ${tab === "weekly" ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>Weekly Plan</button><button onClick={() => setTab("grocery")} className={`whitespace-nowrap border-b-2 px-3 py-2 text-sm ${tab === "grocery" ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>Grocery</button></div>
    {tab === "today" && <div className="space-y-6"><Section title="Today's targets" meta={entry ? `已记录 · ${entry.carbDay} carb day` : "尚未记录"}><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Panel><p className="text-xs text-muted-foreground">热量</p><p className="mt-1 text-xl font-semibold">{entry?.calories ?? 0} <span className="text-xs font-normal">/ {target.calories}</span></p><ProgressBar value={entry?.calories ?? 0} max={target.calories} tone="bg-orange-500" /></Panel><Panel><p className="text-xs text-muted-foreground">蛋白质</p><p className="mt-1 text-xl font-semibold">{entry?.protein ?? 0} <span className="text-xs font-normal">/ {target.protein} g</span></p><ProgressBar value={entry?.protein ?? 0} max={target.protein} /></Panel><Panel><p className="text-xs text-muted-foreground">水果</p><p className="mt-1 text-xl font-semibold">{entry?.fruitServings ?? 0} <span className="text-xs font-normal">/ {target.fruit}</span></p><ProgressBar value={entry?.fruitServings ?? 0} max={target.fruit} tone="bg-emerald-500" /></Panel><Panel><p className="text-xs text-muted-foreground">蔬菜</p><p className="mt-1 text-xl font-semibold">{entry?.vegetableServings ?? 0} <span className="text-xs font-normal">/ {target.vegetables}</span></p><ProgressBar value={entry?.vegetableServings ?? 0} max={target.vegetables} tone="bg-emerald-500" /></Panel></div></Section><Section title="Standard Home Diet"><Panel><div className="flex items-start gap-3"><Utensils className="mt-0.5 h-5 w-5 text-amber-500" /><div className="flex-1"><p className="font-medium">Standard Home Diet</p><p className="mt-1 text-sm text-muted-foreground">米饭 + 鸡胸肉 + 蔬菜，鸡蛋另备；份量可按训练日碳水分类缩放。</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm md:grid-cols-4"><span>鸡胸肉 300–350 g</span><span>鸡蛋 3 个</span><span>牛奶 500 ml</span><span>水果 2 份</span></div></div></div></Panel></Section></div>}
    {tab === "templates" && <Section title="Meal Templates" meta="可缩放，数量会同步到 Grocery"><div className="grid gap-3 md:grid-cols-2">{state.mealTemplates.map(t => <Panel key={t.id}><div className="flex items-start gap-3"><span className="text-2xl">{t.emoji}</span><div className="flex-1"><p className="font-medium">{t.label}</p><p className="mt-1 text-sm text-muted-foreground">{t.rice.amount} 米饭 · {t.meat.amount} {t.meat.name} · {t.greenVeg.amount} {t.greenVeg.name}</p><div className="mt-3 flex gap-4 text-xs text-muted-foreground"><span>{t.dayTotalKcal} kcal</span><span>P {t.macros.protein} g</span><span>C {t.macros.carbs} g</span><span>F {t.macros.fat} g</span></div></div></div></Panel>)}</div></Section>}
    {tab === "weekly" && <Section title="Weekly meal planning"><Panel><div className="grid gap-4 sm:grid-cols-3"><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">计划周期</span><input value="7" readOnly className="w-full rounded-md border border-input bg-background px-3 py-2" /></label><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">预计居家餐</span><input value="14" readOnly className="w-full rounded-md border border-input bg-background px-3 py-2" /></label><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">预计社交餐</span><input defaultValue="3" className="w-full rounded-md border border-input bg-background px-3 py-2" /></label></div><p className="mt-4 text-sm text-muted-foreground">社交餐不会被视为失败。填写频率即可，系统会从居家采购量中扣除，不要求精确计算餐厅热量。</p></Panel></Section>}
    {tab === "grocery" && <Section title="Grocery checklist" meta="营养单位与购物单位分开"><div className="mb-3 flex items-center justify-between"><p className="text-sm text-muted-foreground">按 7 天、14 个居家餐估算</p><button onClick={generate} className="flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"><ShoppingCart className="h-4 w-4" /> Generate Grocery List</button></div><Panel>{Object.entries(grouped).map(([category, categoryItems]) => <div key={category} className="mb-5 last:mb-0"><h3 className="mb-1 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{category}</h3>{categoryItems.map(item => <CheckRow key={item.id} checked={item.checked} onChange={() => update(s => ({ ...s, grocery: items.map(i => i.id === item.id ? { ...i, checked: !i.checked } : i) }))}><span className="text-sm">{item.name} <span className="text-muted-foreground">· {item.required} {item.unit} · 购买 {item.purchase}</span></span></CheckRow>)}</div>)}</Panel><button onClick={() => update(s => ({ ...s, groceryHistory: [...s.groceryHistory, { date: today, items }] }))} className="mt-3 flex items-center gap-2 text-sm text-primary"><Check className="h-4 w-4" /> Mark Shopping Complete</button></Section>}
  </div>;
}
