import { useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Dumbbell, Pencil, Plus, Timer, Waves } from "lucide-react";
import { useLocation } from "wouter";
import { PageHeader, Panel, Section } from "@/components/os-ui";
import { PHASES, addDays, formatDate, startOfWeek, uid, useFitnessStore, type ActivityEntry } from "@/lib/localStore";
import { CORE_FOCUS_LABELS, CORE_MOVEMENTS, DEFAULT_STRENGTH_PROGRAMS, SPORT_SESSION_TYPES, phase0RirForWeek, type CoreFocus, type StrengthProgram, type TrainingSessionKind } from "@shared/strengthPrograms";
import { DEFAULT_WEEKLY_SCHEDULE, phaseWeekForDate, type WeeklyScheduleEntry } from "@shared/trainingPlan";

function plannedSets(program: StrengthProgram, targetRir: string) {
  return program.exercises.flatMap(exercise => Array.from({ length: exercise.sets }, () => ({ exercise: exercise.name, targetReps: exercise.repRange, targetRir })));
}

export default function Plan() {
  const { state, update } = useFitnessStore();
  const [, go] = useLocation();
  const [weekOffset, setWeekOffset] = useState(0);
  const [showTemplates, setShowTemplates] = useState(false);
  const [editingSchedule, setEditingSchedule] = useState(false);
  const [scheduleDraft, setScheduleDraft] = useState<WeeklyScheduleEntry[] | null>(null);
  const [editingProgram, setEditingProgram] = useState<StrengthProgram | null>(null);
  const [draftProgram, setDraftProgram] = useState<StrengthProgram | null>(null);
  const week = addDays(startOfWeek(), weekOffset * 7);
  const weekEnd = addDays(week, 6);
  const byDay = useMemo(() => state.activities.filter(a => a.date >= week && a.date <= weekEnd).reduce<Map<string, ActivityEntry[]>>((map, activity) => {
    map.set(activity.date, [...(map.get(activity.date) ?? []), activity]);
    return map;
  }, new Map()), [state.activities, week, weekEnd]);
  const phase = PHASES[state.settings.phase];
  const programs = state.strengthPrograms?.length ? state.strengthPrograms : DEFAULT_STRENGTH_PROGRAMS;
  const schedule = state.weeklySchedule?.length ? state.weeklySchedule : DEFAULT_WEEKLY_SCHEDULE;
  const phaseWeek = phaseWeekForDate(state.settings.phaseStarted, formatDate(), phase.weeks);
  const targetRir = state.settings.phase === "phase0" ? phase0RirForWeek(phaseWeek) : "2–3";
  const targetRirForDate = (date: string) => state.settings.phase === "phase0" ? phase0RirForWeek(phaseWeekForDate(state.settings.phaseStarted, date, phase.weeks)) : "2–3";

  const addPlanned = (date: string, item: WeeklyScheduleEntry) => {
    const program = item.programId ? programs.find(p => p.id === item.programId) : undefined;
    update(current => ({ ...current, activities: [...current.activities, {
      id: uid("activity"), date, type: item.type ?? "other", title: item.title, durationMin: program ? 60 : item.type === "swimming" ? 45 : item.type === "core" ? 30 : 90,
      sessionType: item.sessionType, coreFocus: item.coreFocus, completed: false, notes: item.secondary, sets: program ? plannedSets(program, targetRirForDate(date)) : undefined,
    }] }));
  };

  const addSport = (kind: TrainingSessionKind) => {
    const title = kind === "swimming" ? "游泳" : kind === "tennis" ? "网球" : "拳击";
    addPlanned(formatDate(), { id: uid("schedule"), dayIndex: 0, day: "", title, type: kind, sessionType: SPORT_SESSION_TYPES[kind][0], secondary: "计划 session" });
    setShowTemplates(false);
  };

  const toggleCompleted = (id: string) => update(current => ({ ...current, activities: current.activities.map(a => a.id === id ? { ...a, completed: !a.completed } : a) }));
  const beginEdit = (program: StrengthProgram) => { setEditingProgram(program); setDraftProgram(JSON.parse(JSON.stringify(program)) as StrengthProgram); };
  const saveProgram = () => { if (!draftProgram) return; update(current => ({ ...current, strengthPrograms: programs.map(program => program.id === draftProgram.id ? draftProgram : program) })); setEditingProgram(null); setDraftProgram(null); };
  const beginScheduleEdit = () => { setEditingSchedule(true); setScheduleDraft(JSON.parse(JSON.stringify(schedule)) as WeeklyScheduleEntry[]); };
  const saveSchedule = () => { if (!scheduleDraft) return; update(current => ({ ...current, weeklySchedule: scheduleDraft })); setEditingSchedule(false); setScheduleDraft(null); };
  const updateScheduleEntry = (index: number, patch: Partial<WeeklyScheduleEntry>) => setScheduleDraft(current => current?.map((entry, entryIndex) => entryIndex === index ? { ...entry, ...patch } : entry) ?? null);

  return <div className="pb-10">
    <PageHeader eyebrow="Plan" title="训练计划" description="先安排主要 session，再在每日记录中填写真实完成情况。" action={<div className="flex items-center gap-2"><button onClick={() => setShowTemplates(v => !v)} className="flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-sm"><Plus className="h-4 w-4" /> 添加训练</button><button onClick={() => go(`/log?date=${formatDate()}`)} className="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground">今日记录</button></div>} />
    {showTemplates && <Panel className="mb-6"><div className="mb-3 flex items-center justify-between"><p className="font-medium">快速添加 session</p><button onClick={() => setShowTemplates(false)} className="text-sm text-muted-foreground">关闭</button></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{programs.map(program => <button key={program.id} onClick={() => { addPlanned(formatDate(), { id: uid("schedule"), dayIndex: 0, day: "", title: program.title, type: "strength", programId: program.id, secondary: `目标 RIR ${targetRir}` }); setShowTemplates(false); }} className="rounded-md border border-border p-3 text-left hover:border-primary"><Dumbbell className="h-4 w-4 text-primary" /><p className="mt-2 text-sm font-medium">{program.title}</p><p className="mt-1 text-xs text-muted-foreground">{program.exercises.length} 个动作 · RIR {targetRir}</p></button>)}{(["swimming", "tennis", "boxing"] as TrainingSessionKind[]).map(kind => <button key={kind} onClick={() => addSport(kind)} className="rounded-md border border-border p-3 text-left hover:border-primary"><Waves className="h-4 w-4 text-primary" /><p className="mt-2 text-sm font-medium">{kind === "swimming" ? "游泳" : kind === "tennis" ? "网球" : "拳击"}</p><p className="mt-1 text-xs text-muted-foreground">{SPORT_SESSION_TYPES[kind].join(" · ")}</p></button>)}<button onClick={() => { addPlanned(formatDate(), { id: uid("schedule"), dayIndex: 0, day: "", title: "核心训练", type: "core", sessionType: "anti-extension", coreFocus: "anti-extension", secondary: "每周约 3 次，按类型轮换" }); setShowTemplates(false); }} className="rounded-md border border-border p-3 text-left hover:border-primary"><Waves className="h-4 w-4 text-primary" /><p className="mt-2 text-sm font-medium">核心训练</p><p className="mt-1 text-xs text-muted-foreground">{Object.values(CORE_FOCUS_LABELS).join(" · ")}</p></button></div></Panel>}
    <Section title="Current phase"><Panel className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-lg font-semibold">{phase.label}</p><p className="text-sm text-muted-foreground">{phase.subtitle}</p></div><button onClick={() => go("/settings")} className="flex items-center gap-2 text-sm text-primary"><Pencil className="h-4 w-4" /> 阶段设置</button></Panel></Section>
    <Section title="Weekly architecture" meta={<div className="flex items-center gap-2"><button aria-label="上一周" onClick={() => setWeekOffset(offset => offset - 1)} className="rounded border border-border p-1"><ChevronLeft className="h-4 w-4" /></button><span>{week} → {weekEnd}</span><button aria-label="下一周" onClick={() => setWeekOffset(offset => offset + 1)} className="rounded border border-border p-1"><ChevronRight className="h-4 w-4" /></button><button onClick={beginScheduleEdit} className="ml-2 flex items-center gap-1 text-primary"><Pencil className="h-3.5 w-3.5" />编辑周结构</button></div>}>
      <div className="space-y-2">{schedule.slice().sort((a, b) => a.dayIndex - b.dayIndex).map(item => { const date = addDays(week, item.dayIndex); const logged = byDay.get(date) ?? []; return <Panel key={`${item.id}-${date}`} className="flex flex-wrap items-center gap-3 py-3"><div className="w-12 shrink-0 text-sm font-semibold">{item.day}</div><div className="min-w-40 flex-1"><p className="text-sm font-medium">{item.title}</p><p className="text-xs text-muted-foreground">{item.secondary}</p></div><div className="flex min-w-48 flex-1 flex-wrap gap-1">{logged.length ? logged.map(activity => <button key={activity.id} onClick={() => toggleCompleted(activity.id)} className={`flex items-center gap-1 rounded px-2 py-1 text-xs ${activity.completed ? "bg-emerald-500/10 text-emerald-600" : "bg-muted text-muted-foreground"}`}><Check className="h-3 w-3" />{activity.title}</button>) : <span className="text-xs text-muted-foreground">未安排</span>}</div><button onClick={() => addPlanned(date, item)} className="flex items-center gap-1 rounded-md border border-border px-2 py-1.5 text-xs"><Plus className="h-3 w-3" />安排</button><button onClick={() => go(`/log?date=${date}`)} className="rounded-md bg-secondary px-2 py-1.5 text-xs">记录</button></Panel>; })}</div>
    </Section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><Section title="Strength program" meta={`Phase 0：当前目标 RIR ${targetRir}`}><Panel><div className="space-y-3">{programs.map(program => <div key={program.id} className="border-b border-border/50 pb-3 last:border-0 last:pb-0"><div className="flex items-start gap-3"><Dumbbell className="mt-1 h-4 w-4 text-primary" /><div className="flex-1"><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">{program.title}</p><button onClick={() => beginEdit(program)} aria-label={`编辑 ${program.title}`} className="text-muted-foreground"><Pencil className="h-4 w-4" /></button></div><p className="text-xs text-muted-foreground">{program.description}</p><div className="mt-2 flex flex-wrap gap-1">{program.exercises.map(exercise => <span key={exercise.id} className="rounded bg-muted px-2 py-1 text-xs">{exercise.name} · {exercise.sets}×{exercise.repRange} · RIR {exercise.targetRir}</span>)}</div></div></div></div>)}</div></Panel></Section><Section title="Core rotation"><Panel><div className="space-y-2 text-sm">{(Object.keys(CORE_FOCUS_LABELS) as CoreFocus[]).map(focus => <div key={focus} className="flex items-center justify-between gap-3 border-b border-border/50 py-2 last:border-0"><span>{CORE_FOCUS_LABELS[focus]}</span><span className="text-right text-xs text-muted-foreground">{CORE_MOVEMENTS[focus].map(movement => movement.name).join(" · ")}</span></div>)}</div><p className="mt-3 text-xs text-muted-foreground">核心约每周 3 次，按四种类型轮换。</p></Panel></Section><Section title="Session rules"><Panel className="space-y-3 text-sm"><div className="flex items-start gap-3"><Timer className="mt-0.5 h-4 w-4 text-primary" /><p>每天通常只安排一个主要高压力 session；额外训练保持轻松或技术性。</p></div><p className="text-xs text-muted-foreground">力量训练支持双重进阶。记录每组重量、次数和 RIR，不鼓励常规力竭。</p></Panel></Section></div>
    {editingProgram && draftProgram && <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4"><Panel className="max-h-[90vh] w-full max-w-2xl overflow-y-auto"><div className="flex items-center justify-between"><div><p className="text-lg font-semibold">编辑 {draftProgram.title}</p><p className="text-sm text-muted-foreground">修改动作、替代动作、组数和目标次数会应用到后续计划。</p></div><button onClick={() => setEditingProgram(null)} className="text-sm text-muted-foreground">关闭</button></div><div className="mt-5 space-y-3">{draftProgram.exercises.map((exercise, index) => <div key={exercise.id} className="grid gap-2 rounded-md border border-border/70 p-3 sm:grid-cols-[1.4fr_70px_100px_100px]"><input aria-label="动作" value={exercise.name} onChange={e => setDraftProgram({ ...draftProgram, exercises: draftProgram.exercises.map((item, i) => i === index ? { ...item, name: e.target.value } : item) })} className="rounded border border-input bg-background px-2 py-1.5 text-sm" /><input aria-label="组数" type="number" min="1" max="8" value={exercise.sets} onChange={e => setDraftProgram({ ...draftProgram, exercises: draftProgram.exercises.map((item, i) => i === index ? { ...item, sets: Number(e.target.value) || 1 } : item) })} className="rounded border border-input bg-background px-2 py-1.5 text-sm" /><input aria-label="次数范围" value={exercise.repRange} onChange={e => setDraftProgram({ ...draftProgram, exercises: draftProgram.exercises.map((item, i) => i === index ? { ...item, repRange: e.target.value } : item) })} className="rounded border border-input bg-background px-2 py-1.5 text-sm" /><input aria-label="RIR" value={exercise.targetRir} onChange={e => setDraftProgram({ ...draftProgram, exercises: draftProgram.exercises.map((item, i) => i === index ? { ...item, targetRir: e.target.value } : item) })} className="rounded border border-input bg-background px-2 py-1.5 text-sm" /><input aria-label="替代动作" value={exercise.alternatives.join(", ")} onChange={e => setDraftProgram({ ...draftProgram, exercises: draftProgram.exercises.map((item, i) => i === index ? { ...item, alternatives: e.target.value.split(",").map(value => value.trim()).filter(Boolean) } : item) })} placeholder="替代动作，用逗号分隔" className="rounded border border-input bg-background px-2 py-1.5 text-sm sm:col-span-4" /></div>)}</div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setEditingProgram(null)} className="rounded-md border border-border px-3 py-2 text-sm">取消</button><button onClick={saveProgram} className="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground">保存计划</button></div></Panel></div>}
    {editingSchedule && scheduleDraft && <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4"><Panel className="max-h-[90vh] w-full max-w-2xl overflow-y-auto"><div className="flex items-center justify-between"><div><p className="text-lg font-semibold">编辑每周训练结构</p><p className="text-sm text-muted-foreground">只修改默认周结构，不会改变已经记录的历史 session。</p></div><button onClick={() => { setEditingSchedule(false); setScheduleDraft(null); }} className="text-sm text-muted-foreground">关闭</button></div><div className="mt-5 space-y-3">{scheduleDraft.map((entry, index) => <div key={entry.id} className="space-y-2 rounded-md border border-border/70 p-3"><p className="text-sm font-semibold">{entry.day}</p><div className="grid gap-2 sm:grid-cols-2"><input aria-label={`${entry.day} 主训练`} value={entry.title} onChange={e => updateScheduleEntry(index, { title: e.target.value })} className="rounded border border-input bg-background px-2 py-1.5 text-sm" placeholder="主训练" /><select aria-label={`${entry.day} 类型`} value={entry.type} onChange={e => updateScheduleEntry(index, { type: e.target.value as WeeklyScheduleEntry["type"], programId: e.target.value === "strength" ? entry.programId : undefined })} className="rounded border border-input bg-background px-2 py-1.5 text-sm"><option value="strength">力量</option><option value="swimming">游泳</option><option value="tennis">网球</option><option value="boxing">拳击</option><option value="core">核心</option><option value="other">其他</option></select><input aria-label={`${entry.day} 备注`} value={entry.secondary} onChange={e => updateScheduleEntry(index, { secondary: e.target.value })} className="rounded border border-input bg-background px-2 py-1.5 text-sm" placeholder="可选 session / 备注" /><input aria-label={`${entry.day} Session 类型`} value={entry.sessionType ?? ""} onChange={e => updateScheduleEntry(index, { sessionType: e.target.value || undefined })} className="rounded border border-input bg-background px-2 py-1.5 text-sm" placeholder="Session 类型" /></div>{entry.type === "strength" && <select aria-label={`${entry.day} 力量计划`} value={entry.programId ?? ""} onChange={e => updateScheduleEntry(index, { programId: e.target.value ? e.target.value as StrengthProgram["id"] : undefined })} className="w-full rounded border border-input bg-background px-2 py-1.5 text-sm"><option value="">不套用力量计划</option>{programs.map(program => <option key={program.id} value={program.id}>{program.title}</option>)}</select>}</div>)}</div><div className="mt-5 flex justify-end gap-2"><button onClick={() => { setEditingSchedule(false); setScheduleDraft(null); }} className="rounded-md border border-border px-3 py-2 text-sm">取消</button><button onClick={saveSchedule} className="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground">保存周结构</button></div></Panel></div>}
  </div>;
}
