import { useMemo, useState } from "react";
import { Check, ChevronDown, Dumbbell, Pencil, Plus, Waves } from "lucide-react";
import { PageHeader, Panel, Section } from "@/components/os-ui";
import { PHASES, startOfWeek, uid, useFitnessStore, type ActivityEntry } from "@/lib/localStore";
import { WORKOUT_TEMPLATES } from "@shared/workoutTemplates";

const schedule = [
  ["周一", "力量 A", "可选：轻松游"], ["周二", "网球", "Rally / Coaching"], ["周三", "游泳", "可选：核心"], ["周四", "力量 B", "可选：轻松游"], ["周五", "网球", "Rally / Match"], ["周六", "力量 C", "可选：拳击"], ["周日", "恢复游 / 灵活性", "或完全休息"],
];

export default function Plan() {
  const { state, update, add } = useFitnessStore(); const [showTemplates, setShowTemplates] = useState(false); const [editingPhase, setEditingPhase] = useState(false);
  const week = startOfWeek(); const byDay = useMemo(() => new Map(state.activities.filter(a => a.date >= week).map(a => [a.date, a])), [state.activities, week]);
  const phase = PHASES[state.settings.phase];
  const claim = (templateId: string) => { const t = WORKOUT_TEMPLATES.find(item => item.id === templateId); if (!t) return; add("activities", { id: uid("activity"), date: new Date().toISOString().slice(0, 10), type: t.category === "cardio" ? "swimming" : "strength", title: t.title, durationMin: t.sessionA?.durationMin ?? 45, completed: false, notes: t.description } as ActivityEntry); setShowTemplates(false); };
  return <div className="pb-10"><PageHeader eyebrow="Plan" title="计划" description="一周只需要知道下一次该做什么，细节在记录时完成。" action={<button onClick={() => setShowTemplates(v => !v)} className="flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-sm"><Plus className="h-4 w-4" /> 添加训练</button>} />
    {showTemplates && <Panel className="mb-6"><div className="mb-3 flex items-center justify-between"><p className="font-medium">选择训练模板</p><button onClick={() => setShowTemplates(false)} className="text-sm text-muted-foreground">关闭</button></div><div className="grid gap-2 md:grid-cols-3">{WORKOUT_TEMPLATES.map(t => <button key={t.id} onClick={() => claim(t.id)} className="rounded-md border border-border p-3 text-left hover:border-primary"><p className="text-sm font-medium">{t.title}</p><p className="mt-1 text-xs text-muted-foreground">{t.description}</p></button>)}</div></Panel>}
    <Section title="Current phase"><Panel className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-lg font-semibold">{phase.label}</p><p className="text-sm text-muted-foreground">{phase.subtitle}</p></div>{editingPhase ? <select value={state.settings.phase} onChange={e => { const phaseId = e.target.value as keyof typeof PHASES; update(s => ({ ...s, settings: { ...s.settings, phase: phaseId, phaseDurationWeeks: PHASES[phaseId].weeks, phaseStarted: new Date().toISOString().slice(0, 10) } })); setEditingPhase(false); }} className="rounded-md border border-input bg-background px-3 py-2 text-sm">{Object.entries(PHASES).map(([id, p]) => <option key={id} value={id}>{p.label}</option>)}</select> : <button onClick={() => setEditingPhase(true)} className="flex items-center gap-2 text-sm text-primary"><Pencil className="h-4 w-4" /> 手动切换阶段</button>}</Panel></Section>
    <Section title="Weekly architecture" meta="Phase 0 默认安排"><div className="space-y-2">{schedule.map(([day, primary, secondary], index) => { const date = new Date(week); date.setDate(date.getDate() + index); const dateStr = date.toISOString().slice(0, 10); const logged = byDay.get(dateStr); return <Panel key={day} className="flex items-center gap-3 py-3"><div className="w-12 shrink-0 text-sm font-semibold">{day}</div><div className="flex-1"><p className="text-sm font-medium">{primary}</p><p className="text-xs text-muted-foreground">{secondary}</p></div>{logged ? <span className={`flex items-center gap-1 text-xs ${logged.completed ? "text-emerald-500" : "text-muted-foreground"}`}><Check className="h-4 w-4" />{logged.title}</span> : <span className="text-xs text-muted-foreground">未记录</span>}<ChevronDown className="h-4 w-4 text-muted-foreground" /></Panel>; })}</div></Section>
    <div className="mt-6 grid gap-6 md:grid-cols-2"><Section title="Strength program"><Panel><div className="space-y-3">{["Strength A", "Strength B", "Strength C"].map((name, i) => <div key={name} className="flex items-center gap-3 border-b border-border/50 pb-3 last:border-0 last:pb-0"><Dumbbell className="h-4 w-4 text-primary" /><div className="flex-1"><p className="text-sm font-medium">{name}</p><p className="text-xs text-muted-foreground">{i === 0 ? "深蹲 · 卧推 · 高位下拉 · 侧平举 · 腹部" : i === 1 ? "罗马尼亚硬拉 · 上斜推 · 胸托划船 · 保加利亚分腿蹲" : "腿举 · 引体向上 · 胸推 · 侧平举 · 小腿 · 悬垂举腿"}</p></div><button className="text-muted-foreground" aria-label={`编辑 ${name}`}><Pencil className="h-4 w-4" /></button></div>)}</div></Panel></Section><Section title="Nutrition targets"><Panel><div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-xs text-muted-foreground">热量</p><p className="mt-1 text-lg font-semibold">{state.settings.nutritionTargets.calories} kcal</p></div><div><p className="text-xs text-muted-foreground">蛋白质</p><p className="mt-1 text-lg font-semibold">{state.settings.nutritionTargets.protein} g</p></div><div><p className="text-xs text-muted-foreground">碳水范围</p><p className="mt-1 text-lg font-semibold">{state.settings.nutritionTargets.carbs} g</p></div><div><p className="text-xs text-muted-foreground">脂肪指导</p><p className="mt-1 text-lg font-semibold">{state.settings.nutritionTargets.fat} g</p></div></div><p className="mt-4 text-xs text-muted-foreground">目标可编辑，Phase 0 用真实趋势校准，不自动修改计划。</p></Panel></Section></div>
  </div>;
}
