import { ChangeEvent, useRef, useState } from "react";
import { Download, RotateCcw, Upload } from "lucide-react";
import { PageHeader, Panel, Section } from "@/components/os-ui";
import { defaultState, useFitnessStore, validateStateSnapshot } from "@/lib/localStore";

const inputClass = "w-full rounded-md border border-input bg-background px-3 py-2";
const safeNumber = (value: string, min = 0, max = Number.MAX_SAFE_INTEGER) => { const parsed = Number(value); return Number.isFinite(parsed) ? Math.min(max, Math.max(min, parsed)) : min; };

export default function Settings() {
  const { state, update, exportData, importData, hydrated, fileBacked } = useFitnessStore();
  const fileRef = useRef<HTMLInputElement>(null); const [message, setMessage] = useState(""); const targets = state.settings.nutritionTargets;
  const setTarget = (key: keyof typeof targets, value: string) => update(current => ({ ...current, settings: { ...current.settings, nutritionTargets: { ...current.settings.nutritionTargets, [key]: safeNumber(value, 0, 10000) } } }));
  const setCarbTarget = (day: "low" | "medium" | "high", key: "carbs" | "calories", value: string) => update(current => ({ ...current, settings: { ...current.settings, carbTargets: { ...current.settings.carbTargets, [day]: { ...current.settings.carbTargets[day], [key]: safeNumber(value, 0, 10000) } } } }));
  const setBenchmark = (key: keyof typeof state.settings.performanceBenchmarks, value: string) => update(current => ({ ...current, settings: { ...current.settings, performanceBenchmarks: { ...current.settings.performanceBenchmarks, [key]: value ? safeNumber(value, 0, 100000) : undefined } } }));
  const toggleSubstitutionFood = (foodId: string) => update(current => { const ids = current.settings.proteinSubstitution.foodIds.includes(foodId) ? current.settings.proteinSubstitution.foodIds.filter(id => id !== foodId) : [...current.settings.proteinSubstitution.foodIds, foodId]; return { ...current, settings: { ...current.settings, proteinSubstitution: { ...current.settings.proteinSubstitution, foodIds: ids } } }; });
  const setSubstitutionDays = (value: string) => update(current => { const days = Math.min(7, Math.max(0, Number(value) || 0)); return { ...current, standardHomeDiet: { ...current.standardHomeDiet, fishSubstitutionDays: days }, settings: { ...current.settings, proteinSubstitution: { ...current.settings.proteinSubstitution, daysPerWeek: days } } }; });
  const download = () => { const link = document.createElement("a"); const url = URL.createObjectURL(new Blob([exportData()], { type: "application/json" })); link.href = url; link.download = `fitness-os-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setMessage("已导出备份（包含当前全部本地数据）"); };
  const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024) { setMessage("导入失败：备份文件不能超过 10 MB"); event.target.value = ""; return; } const reader = new FileReader(); reader.onload = () => { try { const json = String(reader.result); const parsed = JSON.parse(json) as Record<string, unknown>; const errors = validateStateSnapshot(parsed); if (errors.length) throw new Error(errors.slice(0, 3).join("；")); const summary = [`训练 ${Array.isArray(parsed.activities) ? parsed.activities.length : 0} 条`, `身体 ${Array.isArray(parsed.body) ? parsed.body.length : 0} 条`, `营养 ${Array.isArray(parsed.nutrition) ? parsed.nutrition.length : 0} 天`].join("、"); if (!window.confirm(`将导入备份并覆盖当前本机数据（${summary}），确定继续吗？`)) return; importData(json); setMessage("已导入备份；本机文件正在更新"); } catch (error) { setMessage(`导入失败：${error instanceof Error ? error.message : "文件格式不正确"}`); } finally { event.target.value = ""; } }; reader.readAsText(file); };
  const restoreDefaults = () => { if (window.confirm("确定恢复默认配置吗？历史记录、模板和购物历史不会删除。")) update(current => ({ ...current, settings: { ...defaultState().settings, name: current.settings.name } })); };
  return <div className="pb-10"><PageHeader eyebrow="Settings" title="设置" description="目标、阶段和单位都由你控制，所有数据保存在本机。" /><div className="space-y-6">
    <Section title="Training phase" meta="阶段切换由你手动确认"><Panel><div className="grid gap-3 sm:grid-cols-3"><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">当前阶段</span><select value={state.settings.phase} onChange={e => { const phase = e.target.value as typeof state.settings.phase; update(current => ({ ...current, settings: { ...current.settings, phase, phaseDurationWeeks: phase === "phase0" ? 6 : phase === "phase1" ? 12 : 20 } })); }} className={inputClass}><option value="phase0">Phase 0 · Reconditioning</option><option value="phase1">Phase 1 · Recomposition / Cut</option><option value="phase2">Phase 2 · Lean Gain</option></select></label><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">阶段开始日期</span><input type="date" value={state.settings.phaseStarted} onChange={e => update(current => ({ ...current, settings: { ...current.settings, phaseStarted: e.target.value || current.settings.phaseStarted } }))} className={inputClass} /></label><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">阶段周期（周）</span><input type="number" min="1" max="104" value={state.settings.phaseDurationWeeks} onChange={e => update(current => ({ ...current, settings: { ...current.settings, phaseDurationWeeks: safeNumber(e.target.value, 1, 104) } }))} className={inputClass} /></label></div><p className="mt-3 text-xs text-muted-foreground">软件只计算阶段周数，不会自动替你切换阶段或修改训练/营养计划。</p></Panel></Section>
    <Section title="Goals"><Panel><div className="grid gap-3 sm:grid-cols-3"><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">身高 (cm)</span><input type="number" min="80" max="250" value={state.settings.heightCm} onChange={e => update(s => ({ ...s, settings: { ...s.settings, heightCm: safeNumber(e.target.value, 80, 250) } }))} className={inputClass} /></label><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">目标体重 (kg)</span><input type="number" min="30" max="300" step="0.1" value={state.settings.targetWeight} onChange={e => update(s => ({ ...s, settings: { ...s.settings, targetWeight: safeNumber(e.target.value, 30, 300) } }))} className={inputClass} /></label><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">目标体脂 (%)</span><input type="number" min="3" max="60" step="0.1" value={state.settings.targetBodyFat} onChange={e => update(s => ({ ...s, settings: { ...s.settings, targetBodyFat: safeNumber(e.target.value, 3, 60) } }))} className={inputClass} /></label></div></Panel></Section>
    <Section title="Nutrition targets" meta="Phase 0 calibration"><Panel><div className="grid gap-3 sm:grid-cols-3">{(["calories", "protein", "carbs", "fat", "fruit", "vegetables"] as const).map(key => <label key={key} className="space-y-1 text-sm"><span className="text-xs capitalize text-muted-foreground">{key}</span><input type="number" min="0" value={targets[key]} onChange={e => setTarget(key, e.target.value)} className={inputClass} /></label>)}</div><p className="mt-3 text-xs text-muted-foreground">目标只用于提示和趋势计算，不会自动修改你的计划。</p></Panel></Section>
    <Section title="Carb-day targets" meta="Low / Medium / High 可独立校准"><Panel><div className="grid gap-3 md:grid-cols-3">{(["low", "medium", "high"] as const).map(day => <div key={day} className="rounded-md border border-border/60 p-3"><p className="text-sm font-medium capitalize">{day}</p><div className="mt-2 grid grid-cols-2 gap-2"><label className="text-xs text-muted-foreground">碳水 (g)<input type="number" min="0" value={state.settings.carbTargets[day].carbs} onChange={e => setCarbTarget(day, "carbs", e.target.value)} className="mt-1 w-full rounded border border-input bg-background px-2 py-1.5 text-sm text-foreground" /></label><label className="text-xs text-muted-foreground">热量<input type="number" min="0" value={state.settings.carbTargets[day].calories} onChange={e => setCarbTarget(day, "calories", e.target.value)} className="mt-1 w-full rounded border border-input bg-background px-2 py-1.5 text-sm text-foreground" /></label></div></div>)}</div></Panel></Section>
    <Section title="Performance benchmarks" meta="用于 Dashboard 对比"><Panel><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{([ ["squat", "深蹲 (kg)"], ["bench", "卧推 (kg)"], ["pulling", "拉类动作 (kg)"], ["longestFreestyleM", "最长自由泳 (m)"] ] as const).map(([key, label]) => <label key={key} className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">{label}</span><input type="number" min="0" step="0.5" placeholder="可选" value={state.settings.performanceBenchmarks[key] ?? ""} onChange={e => setBenchmark(key, e.target.value)} className={inputClass} /></label>)}</div><p className="mt-3 text-xs text-muted-foreground">训练记录中的动作名称会用于匹配当前最佳重量；基准不会自动调整训练计划。</p></Panel></Section>
    <Section title="Protein substitutions" meta="默认每周替换 2 天"><Panel><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">每周替换天数</span><input type="number" min="0" max="7" value={state.settings.proteinSubstitution.daysPerWeek} onChange={e => setSubstitutionDays(e.target.value)} className={inputClass} /></label><div><p className="mb-2 text-xs text-muted-foreground">可用蛋白质替代品（至少选择一种）</p><div className="flex flex-wrap gap-3">{state.foods.filter(food => food.category === "蛋白质" && food.id !== "chicken-breast").map(food => <label key={food.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={state.settings.proteinSubstitution.foodIds.includes(food.id)} onChange={() => toggleSubstitutionFood(food.id)} />{food.name}</label>)}</div></div></div></Panel></Section>
    <Section title="Data portability"><Panel><div className="mb-3 flex items-center gap-2 text-sm"><span className={`h-2.5 w-2.5 rounded-full ${!hydrated ? "bg-amber-500" : fileBacked ? "bg-emerald-500" : "bg-amber-500"}`} /><span>{!hydrated ? "正在连接本地文件存储…" : fileBacked ? "已连接到本地文件存储" : "浏览器回退存储（本地 API 不可用）"}</span></div><div className="flex flex-wrap gap-3"><button onClick={download} className="flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"><Download className="h-4 w-4" /> Export All Data</button><button onClick={() => fileRef.current?.click()} className="flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm"><Upload className="h-4 w-4" /> Import All Data</button><button onClick={restoreDefaults} className="flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm"><RotateCcw className="h-4 w-4" />恢复默认配置</button><input ref={fileRef} type="file" accept="application/json" onChange={upload} className="hidden" /></div>{message && <p className="mt-3 text-sm text-emerald-500">{message}</p>}<p className="mt-3 text-xs text-muted-foreground">JSON 是 canonical backup，包含设置、阶段、训练、身体、营养、恢复、模板和购物历史。</p><p className="mt-2 text-xs text-muted-foreground">本地开发文件：<code className="rounded bg-muted px-1 py-0.5">personal-data/fitness-os.json</code>（已被 Git 忽略）。</p></Panel></Section>
    <Section title="Shopping units"><Panel><div className="grid gap-3 sm:grid-cols-3"><label className="space-y-1 text-sm"><span className="text-xs text-muted-foreground">米饭一杯生重 (g)</span><input type="number" min="1" placeholder="首次使用时填写" value={state.settings.riceCupGrams ?? ""} onChange={e => update(s => ({ ...s, settings: { ...s.settings, riceCupGrams: e.target.value ? Math.max(1, Number(e.target.value) || 0) : undefined } }))} className={inputClass} /></label><div className="rounded-md bg-muted/50 p-3 text-xs text-muted-foreground sm:col-span-2">营养计算统一使用克；Log 支持同时记录杯数，保存时会按此配置换算。牛奶按 1 L，鸡蛋按 12 个装向上取整。</div></div></Panel></Section>
  </div></div>;
}
